global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'adharshkkanagaraj@gmail.com'
  smtp_auth_username: 'Adhi'
  smtp_auth_password: 'Adharsh'
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-slack-notifications'

receivers:
  - name: 'email-slack-notifications'
    email_configs:
      - to: 'admin@company.com'
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .GroupLabels.alertname }}'
        text: '{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']