global:
  scrape_interval: 5s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'python-metrics'
    static_configs:
      - targets: ['python-app:5001'] # Internal Docker DNS will resolve 'python-app'

  - job_name: 'node-metrics'
    static_configs:
      - targets: ['node-app:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:3000'] # Internal Docker DNS handles this

  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:5001']